version: '3.8'

services:
  discord-bot:
    build: .
    container_name: wow-discord-bot
    restart: always
    networks:
      - wow-network
    env_file:
      - .env

networks:
  wow-network:
    external: true
